import React from 'react';

const challenges = [
  // Main Challenges  
  {
    id: 'caesar-cipher',
    titleKey: 'Caesar Cipher Challenge',
    descriptionKey: 'Decode the Caesar cipher to reveal the hidden message.',
    categoryKey: 'cryptography',
    difficultyKey: 'easy',
    points: 30,
    component: React.lazy(() => import('./Challenge1Caesar')),
  },
  {
    id: 'order-matters',
    titleKey: 'Order Matters Challenge',
    descriptionKey: 'Click the buttons in the correct order to solve the challenge.',
    categoryKey: 'logic',
    difficultyKey: 'easy',
    points: 20,
    component: React.lazy(() => import('./Challenge2Order')),
  },
  {
    id: 'ui-bug',
    titleKey: 'UI Bug Challenge',
    descriptionKey: 'Find and exploit the UI bug to access hidden functionality.',
    categoryKey: 'ui',
    difficultyKey: 'medium',
    points: 35,
    component: React.lazy(() => import('./Challenge3UIBug')),
  },
  {
    id: 'url-param',
    titleKey: 'URL Parameter Challenge', 
    descriptionKey: 'Manipulate URL parameters to reveal hidden content.',
    categoryKey: 'web',
    difficultyKey: 'easy',
    points: 25,
    component: React.lazy(() => import('./Challenge4UrlParam')),
  },
  {
    id: 'cookie-challenge',
    titleKey: 'Cookie Challenge',
    descriptionKey: 'Manipulate browser cookies to access restricted content.',
    categoryKey: 'web',
    difficultyKey: 'medium',
    points: 30,
    component: React.lazy(() => import('./Challenge5Cookie')),
  },
  {
    id: 'json-challenge',
    titleKey: 'JSON Challenge',
    descriptionKey: 'Parse and manipulate JSON data to find the hidden flag.',
    categoryKey: 'data',
    difficultyKey: 'medium',
    points: 35,
    component: React.lazy(() => import('./Challenge6Json')),
  },
  {
    id: 'xhr-detective',
    titleKey: 'XHR Detective Challenge',
    descriptionKey: 'Intercept and analyze network requests to find the flag.',
    categoryKey: 'network',
    difficultyKey: 'medium',
    points: 40,
    component: React.lazy(() => import('./Challenge7XHRDetective')),
  },
  {
    id: 'css-debugger',
    titleKey: 'CSS Debugger Challenge',
    descriptionKey: 'Use CSS manipulation to reveal hidden elements.',
    categoryKey: 'ui',
    difficultyKey: 'medium', 
    points: 30,
    component: React.lazy(() => import('./Challenge8CSSDebugger')),
  },
  {
    id: 'cookie-hacker',
    titleKey: 'Cookie Hacker Challenge',
    descriptionKey: 'Advanced cookie manipulation to bypass security measures.',
    categoryKey: 'security',
    difficultyKey: 'hard',
    points: 50,
    component: React.lazy(() => import('./Challenge9CookieHacker')),
  },
  {
    id: 'localstorage-inspector',
    titleKey: 'LocalStorage Inspector Challenge',
    descriptionKey: 'Inspect and manipulate browser localStorage to find secrets.',
    categoryKey: 'web',
    difficultyKey: 'medium',
    points: 35,
    component: React.lazy(() => import('./Challenge10LocalStorageInspector')),
  },
  {
    id: 'broken-dom',
    titleKey: 'Broken DOM Challenge',
    descriptionKey: 'Fix the broken DOM structure to reveal the flag.',
    categoryKey: 'dom',
    difficultyKey: 'medium',
    points: 40,
    component: React.lazy(() => import('./Challenge11BrokenDOM')),
  },
  {
    id: 'json-validator',
    titleKey: 'JSON Validator Challenge',
    descriptionKey: 'Validate and parse complex JSON structures.',
    categoryKey: 'data',
    difficultyKey: 'hard',
    points: 45,
    component: React.lazy(() => import('./Challenge12JSONValidator')),
  },
  {
    id: 'element-highlighter',
    titleKey: 'Element Highlighter Challenge',
    descriptionKey: 'Use element inspection to find highlighted secrets.',
    categoryKey: 'dom',
    difficultyKey: 'easy',
    points: 25,
    component: React.lazy(() => import('./Challenge13ElementHighlighter')),
  },
  {
    id: 'network-timing',
    titleKey: 'Network Timing Challenge',
    descriptionKey: 'Analyze network request timing to find the flag.',
    categoryKey: 'network',
    difficultyKey: 'medium',
    points: 35,
    component: React.lazy(() => import('./Challenge14NetworkTiming')),
  },
  {
    id: 'form-input-fuzzer',
    titleKey: 'Form Input Fuzzer Challenge',
    descriptionKey: 'Test form inputs with various payloads to find vulnerabilities.',
    categoryKey: 'security',
    difficultyKey: 'hard',
    points: 50,
    component: React.lazy(() => import('./Challenge15FormInputFuzzer')),
  },
  {
    id: 'race-condition-tester',
    titleKey: 'Race Condition Tester Challenge',
    descriptionKey: 'Identify and exploit race conditions in the application.',
    categoryKey: 'security',
    difficultyKey: 'hard',
    points: 55,
    component: React.lazy(() => import('./Challenge16RaceConditionTester')),
  },
  {
    id: 'dom-mutation-observer',
    titleKey: 'DOM Mutation Observer Challenge',
    descriptionKey: 'Monitor DOM changes to capture dynamic content.',
    categoryKey: 'dom',
    difficultyKey: 'hard',
    points: 45,
    component: React.lazy(() => import('./Challenge17DOMMutationObserver')),
  },
  {
    id: 'accessibility-audit',
    titleKey: 'Accessibility Audit Challenge',
    descriptionKey: 'Find accessibility issues and extract the flag.',
    categoryKey: 'accessibility',
    difficultyKey: 'medium',
    points: 40,
    component: React.lazy(() => import('./Challenge18AccessibilityAudit')),
  }
];

export default challenges; 